### PR TITLE
add doris sink connector

### PR DESCRIPTION
**Pull request by ingdex**
add doris sink connector

### CODE REVIEW

**Comment by sunxiaojian** [comment]
> add doris sink connector

Try to use checkstyle to check the code to ensure that it can pass the check

**Review by odbozhou — COMMENTED** [review]
1. A lot of useless code and commented code
2. Code formatting
3. Is it common to synchronize data to diros? How to handle different schemas? I don't see the logic related to schema processing.

**Comment by francisoliverlee** [comment]
some opts
1. English would be better on this repo, the worlds could see your code and docs, not only Chinese
2. useless code should be removed, such as pom.xml, *.java, 
3. update code style by exec `mvn checkstyle:check` until all passed
4.

**Comment by ingdex** [comment]
Thanks for suggestion, code refactoring has been done.

**Comment by ingdex** [comment]
#299 was closd by accident, new pr is #302

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `enhancement` | Status: **Stale**

This issue has been open since 2022 with no recent activity. 

If this is still relevant, please:
1. Confirm the feature is still needed
2. Check if it has been implemented in a newer version
3. Provide updated context if the requirements have changed

Otherwise, this issue may be closed as stale by maintainers.

---
*Automated evaluation by RockteMQ-AI*

**Pull request closed without merging**
